### ISSUE TITLE
Add JSHint to CI

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/task-router-node#1]
@shyba we're using _JSHint_ as part of our building process. Please add it to this project.

For inspiration you can take a look at https://github.com/TwilioDevEd/employee-directory-node/blob/b9f696ac8964c1a2dab2bc9e7197a59268bf7019/.travis.yml#L9.

### TODO
- [x] Add JSHint dependency.
- [x] Add the `.jshintrc` file.
- [x] Update the `travis.yml` file accordingly.
- [x] Make the check succeeds.
- [x] Enjoy the good work.
